services:
  redis:
    image: redislabs/redismod
    hostname: redis
    networks:
      scrappernetwork:
        aliases:
          - redis

  web:
    build:
      context: .
      target: builder
    # flask requires SIGINT to stop gracefully
    # (default stop signal from Compose is SIGTERM)
    stop_signal: SIGINT
    volumes:
      - .:/code
    networks:
      scrappernetwork:
        aliases:
          - scrapper
      site_sitenetwork:
        aliases:
          - scrapper
    depends_on:
      - redis
networks:
  scrappernetwork:
    driver: bridge
  site_sitenetwork:
    external: true
